### ISSUE TITLE
Optimization for size

### ISSUE THREAD

**Issue by LubosD** [CraneStation/wasi-sdk#30]
I want to implement a simple algorithm in WebAssembly, but adding just `std::vector<float>` into my code adds 250 KB of bloat. Is the prebuilt SDK compiled with `-Os --function-sections --data-sections`?

It seems to me it's not, so I wanted to rebuild it with such CFLAGS, but there are no instructions for the full SDK build. And `docker_build.sh` is currently wrong and broken for several reasons :-(

**Comment by pchickey** [comment]
Hi Lubos, welcome. I think to build with those additional cflags, you'd add them to the `-DCMAKE_C_FLAGS=...` lines in `Makefile`. If adding those flags helps you with code size, I don't see why we wouldn't turn them on by default. Please let us know if it does!

I'm not aware of issues with `docker_build.sh`, it works on my machine, where I use it to build the release tarballs. It is not required to use Docker to build the toolchain, you should be able to use the `Makefile` directly, all docker does is provide a clean sandbox with just the dependencies installed. If you're having any problems with the Docker build or any other parts of the build system, can you open a ticket describing the failure?

**Comment by LubosD** [comment]
There are multiple issues with the docker script - when I just clone (recursively) and run `./docker_build.sh`:

* It forces a rebuild of the Docker image every single time.
  * Because the Dockerfile isn't in a separate directory, it sends the whole file tree (aka "context") to the Docker daemon, which is crazy slow and needless.
* It fails early on due to `/opt/wasi-sdk/bin/clang` not being found within the container. Somehow, it is not being compiled?

I think you should really try running it on a clean system.

**Comment by LubosD** [comment]
![image](https://user-images.githubusercontent.com/878801/57729673-0bb41000-7697-11e9-83c4-e634f3241265.png)

**Comment by kubkon** [comment]
Are you by any chance running it on a Mac?

**Comment by LubosD** [comment]
Nope, Gentoo Linux. But the flavor of the base Linux system shouldn't really matter inside Docker containers.

**Comment by kubkon** [comment]
It indeed shouldn’t. I was just checking because on a Mac it’s not as simple as simply executing the shell script to build the SDK. Anyhow, as @pchickey suggested, did you try building using Makefile directly? Also, when going that route, you could override the `PREFIX` var to point to your local dir in order to avoid `sudo`

**Comment by sunfishcode** [comment]
Addressing the questions at the top:

Wasm doesn't need `-ffunction-sections`; that's for platforms such as ELF which traditionally grouped many things in a .o file into bundles that the linker isn't able to separate. In the wasm .o file format, the linker can always pull out just the functions it needs from a .o file.

The prebuilt SDK is built with -O2 rather than -Os, and while using -Os might help a little, there seems to be something bigger going on here.

Investigating a little, it seems the WASI libcxxabi build is pulling in the "demangling terminate handler" for C++, which is for pretty-printing an exception object in the event that the program is terminated with an unhandled exception. It's pretty big, because it pulls in the whole C++ demangler library. Since WASI's C++ doesn't support exceptions yet, that's not particularly useful here. It looks like we can disable this with the `LIBCXXABI_SILENT_TERMINATE` option. I'll look into this.

**Comment by sunfishcode** [comment]
I've now submitted https://github.com/CraneStation/wasi-sdk/pull/31 which enables `LIBCXXABI_SILENT_TERMINATE`. In a simple test file using `std::vector`, this reduced the binary size by 391340 bytes.

**Comment by sunfishcode** [comment]
#31 is now merged, which should fix the main issue here. Please re-open or file a new issue if there are any further problems!
