### ISSUE TITLE
Strip "opt/wasi-sdk" from filenames in releases

### ISSUE THREAD

**Issue by sbc100** [CraneStation/wasi-sdk#57]
When we untar a release we end up with e.g.

```
wasi-sdk-6.0/opt/wasi-sdk/bin/clang
```

When `wasi-sdk-6.0/bin/clang` would seem more sensible and concise.

I understand the `opt/wasi-sdk` prefix is useful to using during configuration since it means the SDK will work better when installed at this location.  But when unpacked from tarball I don't think its useful since we can't know that final path.

Looks like a simple change to tar_from_installation.sh

**Comment by pchickey** [comment]
Sure, we can do that.

The toolchain will still look for its sysroot inside `/opt/wasi-sdk/...`, unless you know of a configuration option for clang that makes it use a relative path.

**Comment by sbc100** [comment]
No, I don't know how to make the toolchain using relative paths for the default sysroot.  That would be pretty cool.

(Its just the default --sysroot that looks in /opt/wasi-sdk/ right?   Installing to this exact locations is that only way to elide the --sysroot arg.. or is there something else?)

**Comment by pchickey** [comment]
Right, we install in the exact locations so that the user doesnt have to pass `--sysroot /opt/wasi-sdk/whatever`. Its nice for it to all "just work".

I find CMake in general and the llvm project stuff in specific to be pretty impenetrable. I know I've used gcc distributions from tarballs that found their sysroot using a relative path from the executable, and it would be the right choice here too, but I don't have the time to figure it out.

**Comment by sbc100** [comment]
I'll open a separate bug for the relative default sysroot thing.
