### ISSUE TITLE
libfuse: 'sys/statvfs.h' file not found

### ISSUE THREAD

**Issue by ilyaigpetrov** [CraneStation/wasi-sdk#66]
I'm trying to compile [libfuse's hello.c](https://github.com/libfuse/libfuse/blob/master/example/hello.c).
```sh-session
$ /opt/wasi-sdk/bin/clang hello.c `pkg-config fuse3 --cflags --libs` -o demo.wasm
In file included from hello.c:24:
/usr/local/include/fuse3/fuse.h:25:10: fatal error: 'sys/statvfs.h' file not found
#include <sys/statvfs.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```
Can it be resolved?

**Comment by pchickey** [comment]
That header isn't provided with wasi-sdk because the `statvfs` functions it provides are not implemented by WASI.

If you're just trying to get the libfuse example to compile, you could try putting an empty header at `/opt/wasi-sdk/share/wasi-sysroot/include/sys/statvfs.h` and hopefully nothing in that example ends up depending on the definitions that belong in there.

If you have a use case for those particular system functions, we'd have to figure out how to implement it in a way that doesn't break the sandboxing design of WASI, which doesn't seem trivial. The correct forum for that is over in the [WASI standards repo's](https://github.com/webassembly/wasi) issue tracker.
