### ISSUE TITLE
Decoupling wasi-sysroot and LLVM?

### ISSUE THREAD

**Issue by jedisct1** [CraneStation/wasi-sdk#78]
Right now, `wasi-sdk` ships a single big package that includes both `wasi-sysroot`, and a copy of LLVM.

However, systems can already have a recent version of LLVM installed.

On MacOS, for example, the LLVM code included in `wasi-sdk` is useless as it will only run on Linux. But `homebrew` can seamlessly install the latest LLVM version. Most recent Linux and BSD distributions also include LLVM 8 or LLVM 9 packages that can compile to WebAssembly.

As `CraneStation/wasi-libc` doesn't ship any precompiled releases any more, would it make sense to split `wasi-sdk` in two, one package with LLVM for Linux, another package with only `wasi-sysroot`?

**Comment by jedisct1** [comment]
Just realized that it was a duplicate of https://github.com/CraneStation/wasi-sdk/issues/69 :)

**Comment by sbc100** [comment]
wasi-sdk *is* available for macos too.. see wasi-sdk-7.0.  We are just waiting for wasi-sdk-8.0 macos binaries to be uplaoded.  We hope to upload windows version too.

I would still recommend using the pre-compiled sdk that includes the compiler since then you know you are using a test combination.   You also get other things like the cmake config file.
